
name: Android CI (Build APK)

on:
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Verify layout
        run: |
          ls -la
          ls -la app || true

      - name: Set up Gradle (no wrapper)
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: "8.7"

      - name: Build Debug APK
        run: gradle --no-daemon assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: kiosk-debug-apk
          path: app/build/outputs/apk/debug/*.apk
